networks:
  kafka-net:
    driver: bridge
  backend-net:
    driver: bridge
  checkout-db-net:
    driver: bridge
  payment-db-net:
    driver: bridge
  shipping-db-net:
    driver: bridge

volumes:
  checkout_data:
  payment_data:
  shipping_data:
  kafka_data:
  zookeeper_data:

services:
  # Zookeeper para Kafka
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - kafka-net
    volumes:
      - zookeeper_data:/bitnami

  # Broker Kafka
  kafka:
    image: bitnami/kafka:3.5
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1 
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_NAME=PLAINTEXT
      - KAFKA_LISTENER_PORT=9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LOG_RETENTION_HOURS=-1 
    ports:
      - "9092:9092"
    networks: [kafka-net, backend-net]
    volumes:
      - kafka_data:/bitnami

  # Interface Web para Kafka (Kafka UI)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - "8080:8080"
    networks:
      - kafka-net

  # Banco de dados do Checkout (PostgreSQL)
  checkout-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=checkout_user
      - POSTGRES_PASSWORD=checkout_pass
      - POSTGRES_DB=checkout_db
    volumes:
      - checkout_data:/var/lib/postgresql/data
    networks:
      - checkout-db-net
    ports:
      - "5432:5432"

  # Serviço de Checkout
  checkout-service:
    build: ./checkout-service
    depends_on:
      - checkout-db
      - kafka
    env_file:
      - ./checkout-service/.env
    ports:
      - "8081:8080"
    networks: [backend-net, kafka-net, checkout-db-net]

  # Banco de dados do Payment
  payment-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=payment_user
      - POSTGRES_PASSWORD=payment_pass
      - POSTGRES_DB=payment_db
    volumes:
      - payment_data:/var/lib/postgresql/data
    networks:
      - payment-db-net
    ports:
      - "5433:5432"

  # Serviço de Payment
  payment-service:
    build: ./payment-service
    depends_on:
      - payment-db
      - kafka
    env_file:
      - ./payment-service/.env
    ports:
      - "8082:8080"
    networks: [backend-net, kafka-net, payment-db-net]

  # Banco de dados do Shipping
  shipping-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=shipping_user
      - POSTGRES_PASSWORD=shipping_pass
      - POSTGRES_DB=shipping_db
    volumes:
      - shipping_data:/var/lib/postgresql/data
    networks:
      - shipping-db-net
    ports:
      - "5434:5432"

  # Serviço de Shipping
  shipping-service:
    build: ./shipping-service
    depends_on:
      - shipping-db
      - kafka
    env_file:
      - ./shipping-service/.env
    ports:
      - "8083:8080"
    networks: [backend-net, kafka-net, shipping-db-net]

  # BFF (Back-end for Frontend)
  bff:
    build: ./bff
    depends_on:
      - checkout-service
      - payment-service
      - shipping-service
    env_file:
      - ./bff/.env
    ports:
      - "3000:3000"
    networks:
      - backend-net